### ISSUE TITLE
blue and red button do not depress after interacting with it

### ISSUE THREAD

**Issue by shadowblade-03** [ClementLSW/UXG1420-DAA1401-AEP#50]
![photo_2023-03-14_17-02-36](https://user-images.githubusercontent.com/122443939/224949919-5b372ce8-27aa-4ae7-b5bd-0b8c12c7c765.jpg)

also when i press blue button after yellow one which is supposed to be correct the camera shakes?

**Comment by ClementLSW** [comment]
same issue as the spikes, audio manager created from mainmenu
