### ISSUE TITLE
player cannot pass through door on lvl 3

### ISSUE THREAD

**Issue by shadowblade-03** [ClementLSW/UXG1420-DAA1401-AEP#52]
![image](https://user-images.githubusercontent.com/122443939/224953459-76d64764-2a7c-4185-a452-a051b41c45fa.png)

runes all lit up alr

![image](https://user-images.githubusercontent.com/122443939/224953553-d3cd14cd-1c95-44d5-910b-704b2bd30520.png)

**Comment by ClementLSW** [comment]
![image](https://user-images.githubusercontent.com/24468433/224970455-7e8c196a-3de1-4d2f-be13-3c175afdabe1.png)

**Comment by ClementLSW** [comment]
Assign door in the light puzzle script with the door you want to open
